# Generated by Django 5.0.6 on 2024-07-06 09:43

from django.db import migrations, models
from django.db.migrations.migration import SwappableTuple


class Migration(migrations.Migration):

    initial = True

    dependencies: list[SwappableTuple] = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                ("image", models.ImageField(upload_to="projects/")),
                ("description", models.TextField()),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
